<?php

namespace Database\Seeders;

use App\Models\WeddingCard;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class WeddingCardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $samples = [
            [
                'id' => 42,
                'identifyWedding' => 'hung-mai-2026',
                'status' => 'active',
                'customer_email' => 'hungmai@email.com',
                'template' => '1',
                'bride_name' => 'Mai',
                'groom_name' => 'Hùng',
                'wedding_time' => '11:00',
                'wedding_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
                'expires_at' => Carbon::create(2027, 10, 1),
                'created_at' => Carbon::create(2026, 10, 1, 9, 30),
                'banner_preview' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
                'banner_top' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
                'wedding_message' => 'Trân trọng kính mời quý khách đến dự lễ thành hôn của chúng tôi',
                'name_place_wedding' => 'Trung Tâm Tiệc Cưới Melisa Palace',
                'address_wedding' => 'Số 85 Thoại Ngọc Hầu, Phường Hòa Thạnh, Tân Phú, TP. HCM',
                'address_wedding_map' => 'https://maps.google.com',
                'bride_birthday' => '1998-05-12',
                'groom_birthday' => '1996-08-20',
                'bride_avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
                'groom_avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                'des_bride' => 'Cô gái yêu nghệ thuật và nụ cười rạng rỡ',
                'des_groom' => 'Chàng trai yêu thể thao và luôn đồng hành cùng cô dâu',
                'banner_love_story' => '',
                'love_story' => 'Gặp nhau tại đại học, cùng nhau trải qua thanh xuân tươi đẹp.',
                'banner_coundown' => '',
                'album' => json_encode([]),
                'date_coundown' => Carbon::now()->addMonths(2)->format('Y-m-d H:i:s'),
                'address_groom' => 'TP. Hà Nội',
                'address_bride' => 'TP. Hồ Chí Minh',
                'groom_eating_title' => 'Nhà Trai',
                'bride_eating_title' => 'Nhà Gái',
                'groom_eating_date' => Carbon::now()->addMonths(2)->subDays(1)->format('Y-m-d'),
                'bride_eating_date' => Carbon::now()->addMonths(2)->subDays(2)->format('Y-m-d'),
                'time_groom' => '11:00',
                'time_groom_al' => 'Tức ngày 12 tháng 9 năm Bính Ngọ',
                'time_bride' => '11:00',
                'time_bride_al' => 'Tức ngày 11 tháng 9 năm Bính Ngọ',
                'bride_phone' => '0912345678',
                'groom_phone' => '0987654321',
                'message_invite' => 'Sự hiện diện của bạn là niềm hạnh phúc lớn của chúng tôi!',
                'message_gift' => 'Mừng cưới tiện lợi qua mã QR',
                'message_thanks' => 'Chân thành cảm ơn sự yêu thương của mọi người',
                'banner_thanks' => '',
                'groom_qr' => '',
                'bride_qr' => '',
                'groom_map' => '',
                'bride_map' => '',
            ],
            [
                'id' => 41,
                'identifyWedding' => 'tuan-lan',
                'status' => 'locked',
                'customer_email' => 'tuan.le@email.com',
                'template' => '2',
                'bride_name' => 'Lan',
                'groom_name' => 'Tuấn',
                'wedding_time' => '17:30',
                'wedding_date' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'expires_at' => Carbon::create(2027, 9, 28),
                'created_at' => Carbon::create(2026, 9, 28, 14, 15),
                'banner_preview' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
                'banner_top' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
                'wedding_message' => 'Hân hạnh được đón tiếp quý vị trong ngày vui trọng đại',
                'name_place_wedding' => 'White Palace Convention Center',
                'address_wedding' => '194 Hoàng Văn Thụ, Phường 9, Phú Nhuận, TP. HCM',
                'address_wedding_map' => 'https://maps.google.com',
                'bride_birthday' => '1997-11-04',
                'groom_birthday' => '1995-02-18',
                'bride_avatar' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
                'groom_avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                'des_bride' => 'Nàng thơ yêu sự mộc mạc và phong cách cổ điển',
                'des_groom' => 'Chàng kỹ sư chu đáo luôn biết lắng nghe',
                'banner_love_story' => '',
                'love_story' => 'Mối tình 5 năm bắt đầu từ một buổi chiều mưa tại Đà Lạt.',
                'banner_coundown' => '',
                'album' => json_encode([]),
                'date_coundown' => Carbon::now()->addMonths(3)->format('Y-m-d H:i:s'),
                'address_groom' => 'Quận 1, TP. HCM',
                'address_bride' => 'Quận 3, TP. HCM',
                'groom_eating_title' => 'Nhà Trai',
                'bride_eating_title' => 'Nhà Gái',
                'groom_eating_date' => Carbon::now()->addMonths(3)->subDays(1)->format('Y-m-d'),
                'bride_eating_date' => Carbon::now()->addMonths(3)->subDays(2)->format('Y-m-d'),
                'time_groom' => '17:30',
                'time_groom_al' => 'Tức ngày 18 tháng 8 năm Bính Ngọ',
                'time_bride' => '17:30',
                'time_bride_al' => 'Tức ngày 17 tháng 8 năm Bính Ngọ',
                'bride_phone' => '0933112233',
                'groom_phone' => '0909445566',
                'message_invite' => 'Kính mời quý khách chung vui cùng hai bên gia đình',
                'message_gift' => 'Hộp mừng cưới online',
                'message_thanks' => 'Xin chân thành cảm ơn',
                'banner_thanks' => '',
                'groom_qr' => '',
                'bride_qr' => '',
                'groom_map' => '',
                'bride_map' => '',
            ],
            [
                'id' => 40,
                'identifyWedding' => '',
                'status' => 'draft',
                'customer_email' => 'ngoc.nt@email.com',
                'template' => '5',
                'bride_name' => 'Ngọc',
                'groom_name' => 'Minh',
                'wedding_time' => '18:00',
                'wedding_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'expires_at' => null,
                'created_at' => Carbon::create(2026, 10, 3, 16, 45),
                'banner_preview' => 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=600&q=80',
                'banner_top' => 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=1200&q=80',
                'wedding_message' => 'Lễ thành hôn trang trọng theo phong cách Hoàng Gia',
                'name_place_wedding' => 'Gem Center',
                'address_wedding' => '8 Nguyễn Bỉnh Khiêm, Đa Kao, Quận 1, TP. HCM',
                'address_wedding_map' => 'https://maps.google.com',
                'bride_birthday' => '1999-07-21',
                'groom_birthday' => '1997-03-15',
                'bride_avatar' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
                'groom_avatar' => 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
                'des_bride' => 'Nụ cười tỏa nắng',
                'des_groom' => 'Trụ cột vững chắc',
                'banner_love_story' => '',
                'love_story' => 'Từ bạn thân thành bạn đời trọn kiếp.',
                'banner_coundown' => '',
                'album' => json_encode([]),
                'date_coundown' => Carbon::now()->addMonths(4)->format('Y-m-d H:i:s'),
                'address_groom' => 'Hà Nội',
                'address_bride' => 'Đà Nẵng',
                'groom_eating_title' => 'Nhà Trai',
                'bride_eating_title' => 'Nhà Gái',
                'groom_eating_date' => Carbon::now()->addMonths(4)->subDays(1)->format('Y-m-d'),
                'bride_eating_date' => Carbon::now()->addMonths(4)->subDays(2)->format('Y-m-d'),
                'time_groom' => '18:00',
                'time_groom_al' => '',
                'time_bride' => '18:00',
                'time_bride_al' => '',
                'bride_phone' => '0977889900',
                'groom_phone' => '0911223344',
                'message_invite' => 'Kính mời',
                'message_gift' => 'Hộp mừng',
                'message_thanks' => 'Cảm ơn',
                'banner_thanks' => '',
                'groom_qr' => '',
                'bride_qr' => '',
                'groom_map' => '',
                'bride_map' => '',
            ],
            [
                'id' => 39,
                'identifyWedding' => 'quang-anh-thuy-duong',
                'status' => 'active',
                'customer_email' => 'duong.le@gmail.com',
                'template' => '3',
                'bride_name' => 'Thùy Dương',
                'groom_name' => 'Quang Anh',
                'wedding_time' => '10:30',
                'wedding_date' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                'expires_at' => Carbon::now()->addYear(),
                'created_at' => Carbon::create(2026, 9, 25, 10, 0),
                'banner_preview' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
                'banner_top' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
                'wedding_message' => 'Ngày vui đơm hoa kết trái',
                'name_place_wedding' => 'Asiana Plaza',
                'address_wedding' => '45-47 Phan Đăng Lưu, Bình Thạnh, TP. HCM',
                'address_wedding_map' => '',
                'bride_birthday' => '1998-01-01',
                'groom_birthday' => '1995-01-01',
                'bride_avatar' => '',
                'groom_avatar' => '',
                'des_bride' => '',
                'des_groom' => '',
                'banner_love_story' => '',
                'love_story' => '',
                'banner_coundown' => '',
                'album' => json_encode([]),
                'date_coundown' => Carbon::now()->addMonths(1)->format('Y-m-d H:i:s'),
                'address_groom' => 'TP. HCM',
                'address_bride' => 'TP. HCM',
                'groom_eating_title' => 'Nhà Trai',
                'bride_eating_title' => 'Nhà Gái',
                'groom_eating_date' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                'bride_eating_date' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                'time_groom' => '10:30',
                'time_groom_al' => '',
                'time_bride' => '10:30',
                'time_bride_al' => '',
                'bride_phone' => '0988776655',
                'groom_phone' => '0966554433',
                'message_invite' => 'Kính mời',
                'message_gift' => 'Mừng cưới',
                'message_thanks' => 'Cảm ơn',
                'banner_thanks' => '',
                'groom_qr' => '',
                'bride_qr' => '',
                'groom_map' => '',
                'bride_map' => '',
            ],
            [
                'id' => 38,
                'identifyWedding' => 'thanh-hai-ha-my',
                'status' => 'active',
                'customer_email' => 'hai.my2026@gmail.com',
                'template' => '4',
                'bride_name' => 'Hà My',
                'groom_name' => 'Thanh Hải',
                'wedding_time' => '18:00',
                'wedding_date' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'expires_at' => Carbon::now()->addYear(),
                'created_at' => Carbon::create(2026, 9, 20, 11, 20),
                'banner_preview' => 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=600&q=80',
                'banner_top' => 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80',
                'wedding_message' => 'Chân thành kính mời',
                'name_place_wedding' => 'Riverside Palace',
                'address_wedding' => '360D Bến Vân Đồn, Quận 4, TP. HCM',
                'address_wedding_map' => '',
                'bride_birthday' => '1997-06-10',
                'groom_birthday' => '1994-09-12',
                'bride_avatar' => '',
                'groom_avatar' => '',
                'des_bride' => '',
                'des_groom' => '',
                'banner_love_story' => '',
                'love_story' => '',
                'banner_coundown' => '',
                'album' => json_encode([]),
                'date_coundown' => Carbon::now()->addMonths(5)->format('Y-m-d H:i:s'),
                'address_groom' => 'TP. HCM',
                'address_bride' => 'TP. HCM',
                'groom_eating_title' => 'Nhà Trai',
                'bride_eating_title' => 'Nhà Gái',
                'groom_eating_date' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'bride_eating_date' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'time_groom' => '18:00',
                'time_groom_al' => '',
                'time_bride' => '18:00',
                'time_bride_al' => '',
                'bride_phone' => '0944332211',
                'groom_phone' => '0922110099',
                'message_invite' => 'Kính mời',
                'message_gift' => 'Mừng cưới',
                'message_thanks' => 'Cảm ơn',
                'banner_thanks' => '',
                'groom_qr' => '',
                'bride_qr' => '',
                'groom_map' => '',
                'bride_map' => '',
            ]
        ];

        foreach ($samples as $item) {
            WeddingCard::updateOrCreate(['id' => $item['id']], $item);
        }
    }
}
